backend:
  name: git-gateway
  branch: master
  site_domain: etceteradesign.netlify.com

media_folder: /static/img
public_folder: /img

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Next Page Name", name: "nextPageName", widget: "text"}
      - {label: "Previous Page Name", name: "prevPageName", widget: "text"}
